# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheckExchangeRate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckExchangeRate
  pod 'RealmSwift'
  pod 'R.swift'
  pod 'PKHUD'

  target 'CheckExchangeRateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CheckExchangeRateUITests' do
    # Pods for testing
  end

end
